# Generated by Django 4.1.4 on 2023-01-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
